[project]
name = "cauchy-simulations-2025-03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eth-ape==0.7.23",
    "matplotlib>=3.10.1",
    "notebook>=7.3.3",
    "numpy==1.26.4",
    "scipy>=1.15.2",
]
